server:
  port: 8762
spring:
  application:
    name: zuul-school

zuul:
  ignored-services: '*'
  routes:
    customerschool: /customerproxy/**
    classroomschool: /classroomproxy/**
    classcustomerschool: /classcustomerproxy/**
    classcustomerviewschool: /classcustomerviewproxy/**
    