server:
  port: 8080
spring:
  application:
    name: customer-school
  datasource:
    url: jdbc:mysql://localhost/test
    username: dbuser
    password: dbpass
    driverClassName: com.mysql.jdbc.Driver    

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/