server:
  port: 8080

spring:
  application:
    name: web-school
  thymeleaf:
   cache: false
   mode: HTML

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    

