server:
  port: 8084

spring:
  application:
    name: classcustomerview-school
  data:
    mongodb:
      host: localhost
      database: School
  cloud:
    stream:
      bindings:
          ClassCustomerEvent:
            group: classcustomerview
      kafka:
        binder:
          brokers: localhost
          zkNodes: localhost

school:
  classcustomerview:
    transaction:
      timeStoredInMinutes: 60

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/