eureka:
  client:
    enabled: false

spring:
  data:
    mongodb:
      host: localhost
      database: School-SmokeTest
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false
    stream:
      kafka:
        binder:
          brokers: localhost
          zkNodes: localhost
      bindings:
          ClassCustomerEvent:
            group: classcustomerview

stubrunner:
  url: http://localhost:8765
